# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68463a4da4a27c3b80a2f229eb453e5d342321166da1413446ef3b3d0df35a91a645bc5f026fd481c428c4e236c1c7b275af55e751a008efa972777d0c4338f3

test:
  secret_key_base: 037aeaf6216f1abc6554f127d38d2ecba885b484b555cd54d9dd0a821657c64e593137e0c4dd680cc876c0de7f4e7637934c9f8bf7410a5a99a333e7f948c23c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
